version: '3.8'
services:

  # selenium chrome server. vpn connection.
  standalone-chrome:
    container_name: 'selenium_server'
    image: selenium/standalone-chrome-debug:3.141.59
    ports:
      - 5900:5900
      - 4444:4444
    networks:
      - back-tier

  # selenium client app.
  app:
    container_name: 'selenium_client'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - standalone-chrome
    environment:
      SELENIUM_URL: http://standalone-chrome:4444/wd/hub
    tty: true
    command: bash -c "pipenv run test"
    networks:
      - back-tier

# network
networks:
  back-tier:
    driver: bridge
